### PR TITLE
Update CSI sanity tests

### PR DESCRIPTION
**Pull request by WanzenBug**
* Update csi-test package to 3.1.1
* Use 'sanity.' prefix for test binary options
* Add option to generate XML report from test run.
* Run `go test ./...` in CI

### CODE REVIEW

**Comment by WanzenBug** [comment]
Just noticed the `-ginko.reportFile` flag that already creates a junit file, so no need for the custom flag

**Comment by WanzenBug** [comment]
> `-ginkgo.reportFile`

That option turned out to be a lie :-/
re-added our own option

**Comment by WanzenBug** [comment]
@rck Could I ask you to review this one too?

Nothing really exciting in this PR. Just updated the sanity test version and made it pass.

**Comment by rck** [comment]
LGTM

**Pull request merged**
